version: "3"

services:
  osmosisd:
    image: osmolabs/osmosis:8.0.0
    user: "root:root"
    volumes:
      - ./config:/osmosis/.osmosisd/config
      - ./data:/osmosis/.osmosisd/data
      - ./wasm:/osmosis/.osmosisd/wasm
    command:
      - start
    ports:
      - "26657:26657"
      - "1317:1317"
      - "9090:9090"
      - "9091:9091"
