version: "3"

services:
  osmosisd:
    image: osmolabs/osmosis-dev:v9.0.0-rc0-debug
    user: "root:root"
    volumes:
      - ./config:/osmosis/.osmosisd/config
      - ./data:/osmosis/.osmosisd/data
    command:
      - start
    ports:
      - "26657:26657"
      - "1317:1317"
      - "9090:9090"
      - "9091:9091"
